import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <ul>
          <Link href='/home'><a><li>Home</li></a></Link>
          <Link href='/blog'><a><li>Blog</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/contact'><a><li>Contact</li></a></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder Blog Post!
        </h1>

        <p className={styles.description}>
          Get ready for some coding!
          Explore the NEXT.JS blog post!
        </p>

        <div className="blogs">

        </div>
      </main>

    </div>
  )
}
